#!/bin/bash
# Combine binaryFiles into loadable sets.

for samples in ./data/samples/*; do
    for set in A B C; do
        ./util/combine_csvs.py $samples/angle$set $samples/combinedAngle$set.csv
        ./util/combine_csvs.py $samples/$set $samples/combinedBinary$set.csv
    done

    for set in A B C; do
        echo
        angleFile="$samples/combinedAngle$set.csv"
        binaryFile="$samples/combinedBinary$set.csv"

        ls -lh "$angleFile"
        wc -l "$angleFile"
        ls -lh "$binaryFile"
        wc -l "$binaryFile"
        sed 's/.*,//g' "$binaryFile" | sort | uniq -c | grep -v good
    done
done
