#!/bin/bash
# Extract desired data from all files.

destination="data/raw"

mkdir -p "$destination"

while read -r file; do
    name="$(echo "$file" | cut -d/ -f3)"
    echo "Extract $name"
    ./util/extract_from_csv "$name" "$file" "$destination"
done < <(find data/apData -iname '*csv')
