#!/bin/bash -ex
# Prep all files.

sampleSize=10
destination="data/prepped"
destinationGraphImages="data/graphImages"
destinationGraphPDFs="data/graphPDFs"
destinationSamplesClean="data/samples/clean/$sampleSize" # Has no errors.
destinationSamplesDirty="data/samples/dirty/$sampleSize" # Has an error.

mkdir -p "$destination" "$destinationGraphImages" "$destinationGraphPDFs" "$destinationSamplesClean" "$destinationSamplesDirty"

while read -r file; do
    name="$(echo "$file" | cut -d/ -f3)"
    echo "Prep $name"
    ./util/prepCSV "$name" "$file" "$sampleSize" "$destination" "$destinationGraphImages" "$destinationGraphPDFs" "$destinationSamplesClean" "$destinationSamplesDirty"
done < <(find data/raw -iname '*csv')
