#!/bin/bash -ex
# Test prep.

file=2023-06-21-164058.csv
testLocation=/tmp/testPrep

rm -Rfv "$testLocation/"
mkdir -p "$testLocation/"{clean,dirty}

time ./util/prep_csv test data/raw/$file 10 "$testLocation" "$testLocation" "$testLocation" "$testLocation"/clean "$testLocation"/dirty "$testLocation"/clean "$testLocation"/dirty
